apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: memo-app

resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

images:
  - name: sinasdocker/memo-app-image
    newName: docker.io/sinasdocker/memo-app-image
    newTag: e04c23b

#namePrefix: dev- 
