apiVersion: v1
kind: Secret
metadata:
  name: cloudwatch-exporter-scrape
  namespace: monitoring
type: Opaque
stringData:
  cloudwatch-exporter.yaml: |
    - job_name: 'cloudwatch-exporter'
      static_configs:
        - targets: ['cloudwatch-exporter.monitoring.svc.cluster.local:9106']
