apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudwatch-exporter
  namespace: monitoring
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::727646470302:role/eks-cloudwatch-exporter-role