apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - sealed-secret.yaml  
  - ingress.yaml
  # - hpa.yaml
  # - karpenter.yaml
  - servicemonitor.yaml    
  - externaldns/deployment.yaml
  - externaldns/rbac.yaml   
  # - init-configmap.yaml
  # - rds-admin-secret.yaml
  # - db-init-job.yaml

images:
  - name: memo-app-image
    newName: docker.io/sinasdocker/memo-app-image

