apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-secret
  namespace: memo-app
spec:
  encryptedData:
    aws.access.key.id:
    aws.secret.access.key:
    redis.password:
    rds.password:
    rds.endpoint: 
    rds.username: 
    rds.port:  